questions = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "Peter Molyneux was the founder of Bullfrog Productions.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "Tetris is the #1 best-selling video game of all-time.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "Valve&#039;s &quot;Portal&quot; and &quot;Half-Life&quot; franchises exist within the same in-game universe.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
              "correct_answer": "True", "incorrect_answers": ["False"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick Studios&quot;.",
              "correct_answer": "False", "incorrect_answers": ["True"]},
             {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
              "question": "The shotgun appears in every numbered Resident Evil game.",
              "correct_answer": "True", "incorrect_answers": ["False"]}]
